#!/usr/bin/env python

try:
    import cpplint_wrapper
except ImportError:
    # Allows the target to work with an un-sourced workspace.
    import sys, os.path
    sys.path.append(os.path.join(os.path.dirname(os.path.realpath(__file__)), "..", "src"))
    import cpplint_wrapper

cpplint_wrapper.main()
